#!/usr/bin/env bash

# Functions

getAllPersons() {
  curl -X GET \
    "$URL/api/persons"
}

addPerson() {
  curl -X POST \
    "$URL/api/persons" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "name": "'"$newName"'",
        "number": "'"$newNumber"'"
      }'
}

deletePersonById() {
  curl -X DELETE \
    "$URL/api/persons/$id"
}

updatePersonById() {
  curl -X PUT \
    "$URL/api/persons/$id" \
    --header 'Content-Type: application/json' \
    -d '
      {
        "name": "'"$newName"'",
        "number": "'"$newNumber"'"
      }'
}

# Variables

URL="http://localhost:3001"
newName="Merlin Le Singe"
newNumber="1234"
id="60336c88877a2eb04af50bce"

# Samples

#getAllPersons | jq
#addPerson | jq
#deletePersonById | jq
#updatePersonById | jq
